### ISSUE TITLE
MemeGenerator's API appears to be broken.

### ISSUE THREAD

**Issue by blha303** [katylava/memepy#4]
All requests return "Login failed for user 'IIS APPPOOL\MemeGenerator.WebApi.Version1'."

I know this isn't a problem you can fix, but I thought I should bring attention to it.

**Comment by katylava** [comment]
Looks like it was a temporary issue -- 

![grumpy cat cannot reproduce](http://cdn.memegenerator.co/instances/400x/40984929.jpg). 

On another note... 

![github didn't notify me of this issue](http://cdn.memegenerator.co/instances/400x/40984958.jpg)

**Comment by blha303** [comment]
![Silly memegenerator.](http://cdn.memegenerator.co/instances/400x/40985149.jpg)

Yeah, it seems to have resolved itself. Maybe they noticed that their API was broken.
